"""The API for the core functionality."""

from .exceptions import (
    AnimLocatorError,
    AnimLocatorBakeError,
)
from .types import (
    CtrlType,
    ConstraintType,
    OperationType,
)
from .general import (
    get_active_operation,
)
from .ctrl import (
    all_ctrls,
    change_ctrls_type,
    change_ctrls_color,
)
from .anim import (
    get_bake_options,
    get_space_ctrls,
    anim_to_world,
    anim_to_target,
    anim_to_local,
    copy_anim_world,
    copy_anim_local,
    swap_attribute,
    swap_rotate_order,
    is_world_space_available,
    is_target_space_available,
    is_local_space_available,
    is_copy_anim_available,
    is_attribute_swapping_available,
    is_rotate_order_swapping_available,
    constraint_attributes,
    initiate_operation,
    apply_operation,
    cancel_operation,
)
from .utils import (
    index_colors,
    color_index_to_rgb,
    override_object_color,
    get_enum_values,
    has_keys,
    has_constraints,
    gimbal_info,
    gimbal_tolerence,
    gimbal_tolerence_all,
    is_world_space_rotation,
    anim_layers,
)

__all__ = [
    'AnimLocatorError',
    'AnimLocatorBakeError',
    'CtrlType',
    'ConstraintType',
    'OperationType',
    'get_active_operation',
    'all_ctrls',
    'change_ctrls_type',
    'change_ctrls_color',
    'get_bake_options',
    'get_space_ctrls',
    'anim_to_world',
    'anim_to_target',
    'anim_to_local',
    'copy_anim_world',
    'copy_anim_local',
    'swap_attribute',
    'swap_rotate_order',
    'initiate_operation',
    'apply_operation',
    'cancel_operation',
    'is_world_space_available',
    'is_target_space_available',
    'is_local_space_available',
    'is_copy_anim_available',
    'is_attribute_swapping_available',
    'is_rotate_order_swapping_available',
    'constraint_attributes',
    'index_colors',
    'color_index_to_rgb',
    'override_object_color',
    'get_enum_values',
    'has_keys',
    'has_constraints',
    'gimbal_info',
    'gimbal_tolerence',
    'gimbal_tolerence_all',
    'is_world_space_rotation',
    'anim_layers',
]
